/**
 * Inject the per-page OpenGraph image into every docs page's <head>.
 *
 * Starlight already emits og:title/description/url and twitter:card, but no
 * image. This middleware appends og:image + twitter:image pointing at the
 * static PNG generated by src/pages/og/[...slug].png.ts. Both sides key off the
 * collection entry id (e.g. `index`, `guides/architecture`), so the meta tag
 * and the generated file always line up.
 */
import { defineRouteMiddleware } from '@astrojs/starlight/route-data';

export const onRequest = defineRouteMiddleware((context) => {
	const route = context.locals.starlightRoute;
	// In route data the home page's entry id is normalized to the empty slug,
	// whereas getCollection() (used by the image endpoint) keeps it as `index`.
	// Normalize so the meta URL matches the generated file: /og/index.png.
	const id = route.entry.id || 'index';
	const ogImage = new URL(`/og/${id}.png`, context.site ?? context.url.origin);

	route.head.push(
		{ tag: 'meta', attrs: { property: 'og:image', content: ogImage.href } },
		{ tag: 'meta', attrs: { property: 'og:image:width', content: '1200' } },
		{ tag: 'meta', attrs: { property: 'og:image:height', content: '630' } },
		{ tag: 'meta', attrs: { name: 'twitter:image', content: ogImage.href } },
	);
});
